name: Deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar diretório de build
        run: mkdir -p dist

      - name: Empacotar projeto
        run: zip -r dist/devops-learning.zip app.py README.md requirements.txt tests .github

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: devops-learning-artifact
          path: dist/devops-learning.zip
